services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ssi-wxo-api
    restart: always
    ports:
      - "9000:80"   # host:container → host 9000, container 80
    volumes:
      - .:/var/www/html
    networks:
      - network
    depends_on:
      - mysql
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: base64:Fsj1d0fZ24PjfSEntGzEBaZF0IazQA4d18SJxYiMCqk=
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ssi_wxo_api
      DB_USERNAME: laravel
      DB_PASSWORD: secret

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ssi_wxo_api
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    networks:
      - network
    volumes:
      - mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "8080:80"
    networks:
      - network

networks:
  network:

volumes:
  mysql:
